name: Test


on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened


jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_USERNAME: ria
      DB_PASSWORD: ria
      DB_DATABASE: ria

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install Python 3.13
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync --group dev

      - name: Start services
        run: docker compose -f dev.docker-compose.yml up -d db queue --wait

      - name: Run tests
        env:
          APP_NAME: ria
          DB_HOST: localhost
          DB_PORT: 5430
          DB_DATABASE: ria
          DB_PGSCHEMA: ria
          DB_USERNAME: ria
          DB_PASSWORD: ria
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          GEMINI_API_KEY: "YOUR_GEMINI_API_KEY"
          GEMINI_MODEL: "gemini-pro" # Or gemini-2.5-flash
          AWS_ACCESS_KEY_ID: "YOUR_AWS_ACCESS_KEY_ID"
          AWS_SECRET_ACCESS_KEY: "YOUR_AWS_ACCESS_KEY"
          AWS_DEFAULT_REGION: "ap-southeast-2" # Your preferred AWS region
          AWS_BUCKET: "your-s3-bucket-name"
        run: uv run pytest tests/ -v
